# app_attacks/west.yml:
manifest:
  remotes:
    - name: zephyr_attacks
      url-base: https://github.com/HannahGress
  projects:
    - name: zephyr_attacks
      remote: zephyr_attacks
      revision: main
      import: true